### ISSUE TITLE
Feature request - Autogenerate index.yaml

### ISSUE THREAD

**Issue by robertarnesson** [phil-lopreiato/google-cloud-datastore-stub#3]
It would be great if the stub could be used to autogenerate the index.yaml file, i.e. you would run your test suite using the stub and the file would be generated. Similar to the datastore emulator or the python2 dev_appserver that would do this as you run the app locally. I have not looked into it, but the autogeneration code should be in the python appengine sdk, maybe it could be ported relatively easy

**Comment by phil-lopreiato** [comment]
This is an interesting idea, although probably not something that's in scope for this project, as it's intended to replace the legacy NDB's datastore `testbed` implementation, which did not maintain `index.yaml` either
